Avoid error on DM buffer with unknown user
After moving to Enterprise Grid, I started seeing the following error. I
suspect it has something to do with users who are from a different team.

Traceback (most recent call last):
  File "/home/arbab/.weechat/python/autoload/wee_slack.py", line 506, in handle_next
    EVENTROUTER.handle_next()
  File "/home/arbab/.weechat/python/autoload/wee_slack.py", line 494, in handle_next
    self.handlers[function_name](j, self, **kwargs)
  File "/home/arbab/.weechat/python/autoload/wee_slack.py", line 2122, in handle_rtmstart
    channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
  File "/home/arbab/.weechat/python/autoload/wee_slack.py", line 1608, in __init__
    kwargs["name"] = users[dmuser].name
KeyError: u'W4FQFN50C'

Add a check to avoid this.