Sets are not JSON serializable
Commit 46384b6782f0b73318f764bf02f24cdbcdd059c9 introduced storing the
reaction users as a set in the message_json representation. However sets
are not JSON serializable. Instead uses a list and checks for membership
prior to manipulation.

Fixes the traceback:
Traceback (most recent call last):
  File "wee_slack.py", line 2105, in cache_write_cb
    cache_file.write("{}\n".format(json.dumps(message.message_json)))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: set([u'Uxxxxxxxx']) is not JSON serializable