Validate token not empty, before initiate connection (#853)
I continuously received this error:
```
AttributeError: 'NoneType' object has no attribute 'token'
```

Because tokens list was `['', '']`. And wee-chat tried initiate connections without tokens.

This small change fix this error.